version: '3.8'

services:
  memory_scope_main:
    build:
      context: ./
    environment:
      DASHSCOPE_API_KEY: "sk-0000000000"
      # OPENAI_API_KEY: "sk-0000000000"
    volumes:
      - ./memoryscope/core/config:/memory_scope_project/memoryscope/memoryscope/core/config
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    ports:
      - "9200:9200"
    environment:
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      xpack.license.self_generated.type: "trial"
