global_config:
  language: en
  max_workers: 5
  dash_scope_apikey:
  open_ai_apikey:
memory_chat:
  cli_memory_chat:
    class: chat.cli_memory_chat
    memory_service: memory_chat_service
    generation_model: dashscope_generation
memory_service:
  memory_chat_service:
    class: memory.service.base_memory_service
    history_msg_count: 32
    contextual_msg_count: 6
    memory_operations:
      read_user_message:
        class: memory.operation.read_memory
        workflow: dummy
      read_memory:
        class: memory.operation.read_memory
        workflow: dummy
      list_memory:
        class: memory.operation.read_memory
        workflow: dummy
      write_memory:
        class: memory.operation.write_memory
        workflow: dummy
        interval_time: 60
        contextual_msg_count: 6
      summary_memory:
        class: memory.operation.summary_memory
        workflow: dummy
        interval_time: 300
models:
  dashscope_generation:
    clazz: models.llama_index_generation_model
    module_name: DashScope
    model_name: qwen-max
  dashscope_embedding:
    clazz: models.base_embedding_model
    module_name: DashScopeEmbedding
    model_name: text-embedding-v2
  dashscope_rank:
    clazz: models.base_rank_model
    module_name: DashScopeRerank
    model_name: gte-rerank
vector_store:
  clazz: storage.base_vector_store
  index_name: memory_test
  password: ''
monitor:
  clazz: storage.base_monitor
  index_name: memory_test
workers:
  update_insight:
    clazz: worker.summary_long.update_insight
    generation_model: dashscope_generation
    embedding_model: dashscope_embedding
    rank_model: dashscope_rank