global_config:
  language: en
  max_workers: 5
  dash_scope_apikey:
  open_ai_apikey:
memory_chat:
  cli_memory_chat:
    class: chat_v2.cli_memory_chat
    memory_service: memory_chat_service
    generation_model: dashscope_generation
memory_service:
  memory_chat_service:
    class: memory.service.chat_memory_service
    history_msg_count: 32
    contextual_msg_count: 6
    read_memory_key: read_memory
    memory_operations:
      contextual_message:
        class: memory.operation.read_memory
        workflow: dummy
        description: "read session messages of the user"
        contextual_msg_count: 0
      read_memory:
        class: memory.operation.read_memory
        workflow: dummy
        description: "read related memories of the user"
      list_memory:
        class: memory.operation.read_memory
        workflow: dummy
        description: "read all memories of the user"
      write_memory:
        class: memory.operation.write_memory
        workflow: dummy
        description: "write observation memories of the user"
        interval_time: 60
      summary_memory:
        class: memory.operation.summary_memory
        workflow: dummy
        description: "summary observation memories of the user"
        interval_time: 300
models:
  dashscope_generation:
    clazz: models.llama_index_generation_model
    module_name: DashScope
    model_name: qwen-max
  dashscope_embedding:
    clazz: models.base_embedding_model
    module_name: DashScopeEmbedding
    model_name: text-embedding-v2
  dashscope_rank:
    clazz: models.base_rank_model
    module_name: DashScopeRerank
    model_name: gte-rerank
vector_store:
  clazz: storage.base_vector_store
  index_name: memory_test
  password: ''
monitor:
  clazz: storage.base_monitor
  index_name: memory_test
workers:
  update_insight:
    clazz: worker.summary_long.update_insight
    generation_model: dashscope_generation
    embedding_model: dashscope_embedding
    rank_model: dashscope_rank