global_config:
  language: cn
  max_workers: 5

memory_chat:
  cli_memory_chat:
    class: chat.cli_memory_chat
    stream: false
    memory_service: memory_chat_service
    generation_model: dashscope_generation

memory_service:
  memory_chat_service:
    class: memory.service.chat_memory_service
    history_msg_count: 32
    contextual_msg_count: 6
    memory_operations:
      read_message:
        class: memory.operation.read_message
        description: "read session messages of the user"
      read_memory:
        class: memory.operation.read_memory
        workflow: set_query,retrieve_memory1,[extract_time|semantic_rank],fuse_rerank
        description: "read related memories of the user"
      list_memory:
        class: memory.operation.read_memory
        workflow: set_query,retrieve_memory2,print_memory
        description: "read all memories of the user"
      write_memory:
        class: memory.operation.write_memory
        workflow: info_filter,load_memory1,[get_observation|get_observation_with_time],contra_repeat,store_memory
        description: "write observation memories of the user"
        interval_time: 5
#      summary_memory:
#        class: memory.operation.summary_memory
#        workflow: load_memory2,get_reflection_subject,update_insight,long_contra_repeat,store_memory
#        description: "summary observation memories of the user"
#        interval_time: 60

worker:
  dummy:
    class: memory.worker.dummy_worker
    generation_model: dashscope_generation
    embedding_model: dashscope_embedding
    rank_model: dashscope_rank
  set_query:
    class: memory.worker.read.set_query_worker
  retrieve_memory1:
    class: memory.worker.read.retrieve_memory_worker
    retrieve_obs_top_k: 100
    retrieve_ins_pf_top_k: 100
    retrieve_expired_top_k: 0
  extract_time:
    class: memory.worker.read.extract_time_worker
    generation_model: dashscope_generation
    generation_model_top_k: 1
  semantic_rank:
    class: memory.worker.read.semantic_rank_worker
  fuse_rerank:
    class: memory.worker.read.fuse_rerank_worker
    fuse_score_threshold: 0.1
    fuse_ratio_dict:
      conversation: 0.5
      observation: 1
      obs_customized: 1.2
      insight: 2.0
    fuse_time_ratio: 2.0
    fuse_rerank_top_k: 10
  retrieve_memory2:
    class: memory.worker.read.retrieve_memory_worker
    retrieve_obs_top_k: 100
    retrieve_ins_pf_top_k: 100
    retrieve_expired_top_k: 100
  print_memory:
    class: memory.worker.read.print_memory_worker
  info_filter:
    class: memory.worker.write.info_filter_worker
    generation_model: dashscope_generation
    info_filter_msg_max_size: 200
    generation_model_top_k: 1
  load_memory1:
    class: memory.worker.write.load_memory_worker
    retrieve_not_reflected_top_k: 0
    retrieve_not_updated_top_k: 0
    retrieve_insight_top_k: 0
    today_obs_top_k: 100
  get_observation:
    class: memory.worker.write.get_observation_worker
    generation_model: dashscope_generation
    generation_model_top_k: 1
  get_observation_with_time:
    class: memory.worker.write.get_observation_with_time_worker
    generation_model: dashscope_generation
    generation_model_top_k: 1
  contra_repeat:
    class: memory.worker.write.contra_repeat_worker
    generation_model: dashscope_generation
    generation_model_top_k: 1
    retrieve_top_k: 30
    contra_repeat_max_count: 50
  store_memory:
    class: memory.worker.write.store_memory_worker
    store_key: all
  load_memory2:
    class: memory.worker.write.load_memory_worker
    retrieve_not_reflected_top_k: 100
    retrieve_not_updated_top_k: 100
    retrieve_insight_top_k: 100
    today_obs_top_k: 0
  get_reflection_subject:
    class: memory.worker.summary.get_reflection_subject_worker
    retrieve_top_k: 100
    reflect_obs_cnt_threshold: 32
    generation_model_top_k: 1
  update_insight:
    class: memory.worker.summary.update_insight_worker
    update_insight_threshold: 0.1
    generation_model_top_k: 1
    update_insight_max_thread: 10
  long_contra_repeat:
    class: memory.worker.summary.long_contra_repeat_worker
    long_contra_repeat_top_k: 2
    long_contra_repeat_threshold: 0.1
    generation_model_top_k: 1

models:
  dashscope_generation:
    class: models.llama_index_generation_model
    module_name: dashscope_generation
    model_name: qwen-max
  dashscope_embedding:
    class: models.llama_index_embedding_model
    module_name: dashscope_embedding
    model_name: text-embedding-v2
  dashscope_rank:
    class: models.llama_index_rank_model
    module_name: dashscope_rank
    model_name: gte-rerank

memory_store:
  class: storage.llama_index_es_memory_store
  embedding_model: dashscope_embedding
  index_name: memory_index
  es_url: http://localhost:9200
  use_hybrid: false

monitor:
  class: storage.dummy_monitor