global_config:
  language: cn
  max_workers: 5
memory_chat:
  cli_memory_chat:
    class: chat.cli_memory_chat
    memory_service: memory_chat_service
    generation_model: dashscope_generation
    human_name: 用户
    assistant_name: AI
memory_service:
  memory_chat_service:
    class: memory.service.chat_memory_service
    history_msg_count: 32
    contextual_msg_count: 6
    read_memory_key: read_memory
    memory_operations:
      read_message:
        class: memory.operation.read_memory
        workflow: dummy_worker
        description: "read session messages of the user"
      read_memory:
        class: memory.operation.read_memory
        workflow: set_query_worker,[extract_time_worker|retrieve_store_worker,semantic_rank_worker],fuse_rerank_worker
        description: "read related memories of the user"
      list_memory:
        class: memory.operation.read_memory
        workflow: dummy_worker
        description: "read all memories of the user"
      write_memory:
        class: memory.operation.write_memory
        workflow: dummy_worker
        description: "write observation memories of the user"
        interval_time: 60
      summary_memory:
        class: memory.operation.summary_memory
        workflow: dummy_worker
        description: "summary observation memories of the user"
        interval_time: 300
worker:
  dummy_worker:
    class: memory.worker.dummy_worker
    generation_model: dashscope_generation
    embedding_model: dashscope_embedding
    rank_model: dashscope_rank
  set_query_worker:
    class: memory.worker.read.set_query_worker
  extract_time_worker:
    class: memory.worker.read.extract_time_worker
    generation_model_top_k: 1
  retrieve_store_worker:
    class: memory.worker.read.retrieve_store_worker
    retrieve_obs_top_k: 100
    retrieve_ins_pf_top_k: 100
  semantic_rank_worker:
    class: memory.worker.read.semantic_rank_worker
  fuse_rerank_worker:
    class: memory.worker.read.fuse_rerank_worker
    fuse_score_threshold: 0.1
    fuse_ratio_dict:
      conversation: 0.5
      observation: 1
      obs_customized: 1.2
      insight: 2.0
    fuse_time_ratio: 2.0
    fuse_rerank_top_k: 10
  info_filter_worker:
    class: memory.worker.write.info_filter_worker
    generation_model: dashscope_generation
    info_filter_msg_max_size: 200
    generation_model_top_k: 1
  get_observation_worker:
    class: memory.worker.write.get_observation_worker
    generation_model: dashscope_generation
    generation_model_top_k: 1
  get_observation_with_time_worker:
    class: memory.worker.write.get_observation_with_time_worker
    generation_model: dashscope_generation
    generation_model_top_k: 1
  contra_repeat_worker:
    class: memory.worker.write.contra_repeat_worker
    generation_model: dashscope_generation
    generation_model_top_k: 1
    retrieve_top_k: 30
    contra_repeat_max_count: 50
  get_reflection_worker:
    class: memory.worker.summary.get_reflection_worker
    retrieve_top_k: 100
    reflect_obs_cnt_threshold: 32
models:
  dashscope_generation:
    class: models.llama_index_generation_model
    module_name: dashscope_generation
    model_name: qwen-max
  dashscope_embedding:
    class: models.llama_index_embedding_model
    module_name: dashscope_embedding
    model_name: text-embedding-v2
  dashscope_rank:
    class: models.llama_index_rank_model
    module_name: dashscope_rank
    model_name: gte-rerank
vector_store:
  class: storage.llama_index_elastic_search_store
  embedding_model: dashscope_embedding
  index_name: memory_index
  es_url: http://localhost:9200
monitor:
  class: storage.dummy_monitor