global_config:
  language: cn
  max_workers: 5

memory_chat:
  cli_memory_chat:
    class: chat.cli_memory_chat
    memory_service: memory_chat_service
    generation_model: dashscope_generation

memory_service:
  memory_chat_service:
    class: memory.service.chat_memory_service
    contextual_msg_count: 6
    memory_operations:
      read_message:
        class: memory.operation.frontend_operation
        workflow: read_message
        description: "read short memory"

      read_memory:
        class: memory.operation.frontend_operation
        workflow: set_query,[extract_time|retrieve_obs_ins,semantic_rank],fuse_rerank
        description: "read long-term memory"

      list_memory:
        class: memory.operation.frontend_operation
        workflow: set_query,retrieve_top_memory,print_memory
        description: "read all long-term memory of the user"

      delete_memory:
        class: memory.operation.frontend_operation
        workflow: set_query,retrieve_all_memory,delete_memory
        description: "delete a single long-term memory"

      delete_all:
        class: memory.operation.frontend_operation
        workflow: set_query,retrieve_all_memory,delete_all
        description: "delete all long-term memory"

      add_memory:
        class: memory.operation.frontend_operation
        workflow: add_memory
        description: "add a single observation"

      write_memory:
        class: memory.operation.write_memory_op
        workflow: info_filter,[get_observation|get_observation_with_time|load_today_memory],contra_repeat,store_memory
        description: "write observation memory of the user"
        interval_time: 5

      summary_memory:
        class: memory.operation.backend_operation
        workflow: load_obs_and_insight,get_reflection_subject,update_insight,long_contra_repeat,store_memory
        description: "summary observation memory of the user"
        interval_time: 30

worker:
  dummy:
    class: memory.worker.dummy_worker
    generation_model: dashscope_generation
    embedding_model: dashscope_embedding
    rank_model: dashscope_rank
  read_message:
    class: memory.worker.frontend.read_message_worker
  set_query:
    class: memory.worker.frontend.set_query_worker
  retrieve_obs_ins:
    class: memory.worker.frontend.retrieve_memory_worker
    retrieve_obs_top_k: 100
    retrieve_ins_top_k: 100
  extract_time:
    class: memory.worker.frontend.extract_time_worker
    generation_model: dashscope_generation
  semantic_rank:
    class: memory.worker.frontend.semantic_rank_worker
    rank_model: dashscope_rank
  fuse_rerank:
    class: memory.worker.frontend.fuse_rerank_worker
    fuse_score_threshold: 0.05
    fuse_ratio_dict:
      conversation: 0.5
      observation: 1
      obs_customized: 1.2
      insight: 2.0
    fuse_time_ratio: 2.0
    fuse_rerank_top_k: 10
  retrieve_top_memory:
    class: memory.worker.frontend.retrieve_memory_worker
    retrieve_obs_top_k: 100
    retrieve_ins_top_k: 100
    retrieve_expired_top_k: 100
  print_memory:
    class: memory.worker.frontend.print_memory_worker
  retrieve_all_memory:
    class: memory.worker.frontend.retrieve_memory_worker
    retrieve_obs_top_k: 100
    retrieve_ins_top_k: 100
    retrieve_expired_top_k: 100
  delete_memory:
    class: memory.worker.write.update_memory_worker
    method: delete_memory
  delete_all:
    class: memory.worker.write.update_memory_worker
    method: delete_all
  add_memory:
    class: memory.worker.write.update_memory_worker
    method: from_query
  info_filter:
    class: memory.worker.write.info_filter_worker
    generation_model: dashscope_generation
  load_today_memory:
    class: memory.worker.write.load_memory_worker
    retrieve_today_top_k: 100
  get_observation:
    class: memory.worker.write.get_observation_worker
    generation_model: dashscope_generation
  get_observation_with_time:
    class: memory.worker.write.get_observation_with_time_worker
    generation_model: dashscope_generation
  contra_repeat:
    class: memory.worker.write.contra_repeat_worker
    generation_model: dashscope_generation
  store_memory:
    class: memory.worker.write.update_memory_worker
    method: from_memory_key
    memory_key: all
  load_obs_and_insight:
    class: memory.worker.write.load_memory_worker
    retrieve_not_reflected_top_k: 100
    retrieve_not_updated_top_k: 100
    retrieve_insight_top_k: 100
  get_reflection_subject:
    class: memory.worker.summary.get_reflection_subject_worker
  update_insight:
    class: memory.worker.summary.update_insight_worker
  long_contra_repeat:
    class: memory.worker.summary.long_contra_repeat_worker

models:
  dashscope_generation:
    class: models.llama_index_generation_model
    module_name: dashscope_generation
    model_name: qwen-max
  dashscope_embedding:
    class: models.llama_index_embedding_model
    module_name: dashscope_embedding
    model_name: text-embedding-v2
  dashscope_rank:
    class: models.llama_index_rank_model
    module_name: dashscope_rank
    model_name: gte-rerank
  dummy_generation:
    class: models.dummy_generation_model
    module_name: dummy_generation
    model_name: dummy_generation_model

memory_store:
  class: storage.llama_index_es_memory_store
  embedding_model: dashscope_embedding
  index_name: memory_index
  es_url: http://localhost:9200
  use_hybrid: true

monitor:
  class: storage.dummy_monitor