global_config:
  language: cn
  max_workers: 5

memory_chat:
  cli_memory_chat:
    class: chat.cli_memory_chat
    memory_service: memory_chat_service
    generation_model: dummy_generation

memory_service:
  memory_chat_service:
    class: memory.service.chat_memory_service
    history_msg_count: 32
    contextual_msg_count: 6
    memory_operations:
      read_message:
        class: memory.operation.read_message
        description: "read session messages of the user"
      read_memory:
        class: memory.operation.read_memory
        #        workflow: set_query,retrieve_memory1,[extract_time|semantic_rank],fuse_rerank
        workflow: load_memory1
        description: "read related memories of the user"
      write_memory:
        class: memory.operation.write_memory
        workflow: dummy
        description: "write observation memories of the user"
        interval_time: 5

worker:
  dummy:
    class: memory.worker.dummy_worker
    generation_model: dashscope_generation
    embedding_model: dashscope_embedding
    rank_model: dashscope_rank
  load_memory1:
    class: memory.worker.write.load_memory_worker
    retrieve_not_reflected_top_k: 0
    retrieve_not_updated_top_k: 0
    retrieve_insight_top_k: 0
    today_obs_top_k: 100

models:
#  dashscope_generation:
#    class: models.llama_index_generation_model
#    module_name: dashscope_generation
#    model_name: qwen-max
  dashscope_embedding:
    class: models.llama_index_embedding_model
    module_name: dashscope_embedding
    model_name: text-embedding-v2
#  dashscope_rank:
#    class: models.llama_index_rank_model
#    module_name: dashscope_rank
#    model_name: gte-rerank
  dummy_generation:
    class: models.dummy_generation_model
    module_name: dummy_generation
    model_name: dummy_generation_model

memory_store:
  class: storage.llama_index_es_memory_store
  embedding_model: dashscope_embedding
  index_name: ttt
  es_url: http://localhost:9200
  use_hybrid: false

monitor:
  class: storage.dummy_monitor